spring:
  datasource:
    url: jdbc:h2:file:./data/interviewprepdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db/migration

logging:
  level:
    com.interviewprep: DEBUG
    org.springframework.web: DEBUG
