ALTER TABLE interviews ADD COLUMN IF NOT EXISTS confidence_score DOUBLE;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS fear_score DOUBLE;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS shy_score DOUBLE;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS calm_score DOUBLE;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS expression_summary VARCHAR(1000);
