ALTER TABLE users ADD COLUMN IF NOT EXISTS current_streak INT DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS max_streak INT DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active_date DATE;

ALTER TABLE interviews ADD COLUMN IF NOT EXISTS termination_reason VARCHAR(255);
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS violation_count INT DEFAULT 0;
